STRINGS: dict[str, dict[str, object]] = {
    "es": {
        "app_title":          "AgroCommish",
        "configurador_iot":   "Configurador IoT",
        "unidades_listas":    "unidades listas",
        "lang_btn":           "EN",

        "step_1": "Detectar",
        "step_2": "Flashear",
        "step_3": "Configurar",
        "step_4": "Verificar",
        "step_5": "Activar",

        "btn_anterior":          "← Anterior",
        "btn_continuar":         "Continuar →",
        "btn_nuevo_dispositivo": "+ Nuevo dispositivo",

        "s1_header":   "Conecta el ESP32 por USB",
        "s1_sub":      "Se detecta automáticamente al conectar. Compatible con USB-A y USB-C.",
        "s1_esperando":"Esperando dispositivo... conecta el ESP32 por USB",
        "s1_sin_dev":  "(sin dispositivos)",
        "s1_port_no_driver": "Puerto detectado — puede que necesite driver ESP32",

        "s2_header":          "Grabar Firmware",
        "s2_sub":             "Graba el firmware y la app detectará el dispositivo y sus sensores automáticamente.",
        "s2_btn_seleccionar": "Cambiar",
        "s2_btn_grabar":      "Grabar Firmware",
        "s2_grabando":        "Grabando...",
        "s2_reintento":       "Reintentar",
        "s2_ok":              "\n✓  Firmware grabado correctamente.",
        "s2_fw_ok":           "✓  Firmware listo para grabar",
        "s2_fw_missing":      "⚠  firmware.bin no encontrado — selecciona el archivo",
        "s2_log_label":       "Registro del proceso",
        "s2_err_sin_puerto":  "ERROR: Selecciona un puerto primero.",
        "s2_err_fw_noexiste": "ERROR: El archivo firmware.bin no existe en la ruta indicada.",
        "s2_log_puerto": "Puerto: {port}",
        "s2_log_fw":     "Firmware: {fw}",
        "s2_boot_wait":    "⏳  Esperando que el ESP32 reinicie...",
        "s2_dev_id":       "✓  Dispositivo detectado: {did}",
        "s2_boot_timeout": "⚠  El ESP32 no respondió tras el flasheo: {err}\n   Continúa con el paso 3 e intenta escanear redes.",
        "s2_pins_scan":    "🔍  Buscando en qué pines están conectados los sensores...",
        "s2_fase_conectando": "Conectando con el ESP32...",
        "s2_fase_borrando":   "Borrando memoria flash (esto tarda unos segundos)...",
        "s2_fase_grabando":   "Grabando firmware...",
        "s2_fase_verificado": "✓  Verificación de datos correcta",
        "s2_fase_listo":      "✓  Grabación completada",
        "fw_title":      "Seleccionar firmware .bin",
        "fw_filter":     "Firmware ESP32",

        "s3_header":      "Conectar a WiFi",
        "s3_sub":         "Selecciona tu red, ingresa la contraseña y conecta el ESP32.",
        "s3_lbl_redes":   "Redes disponibles",
        "s3_lbl_pass":    "Contraseña",
        "s3_ph_pass":     "Contraseña de la red WiFi",
        "s3_ph_server":   "http://192.168.1.100:5000/api/sensores/lectura",
        "s3_adv_server":  "Configuración avanzada del servidor",
        "s3_btn_escanear":"Buscar redes",
        "s3_btn_conectar":"Conectar al WiFi →",
        "s3_btn_enviar":  "Conectar al WiFi →",
        "s3_enviando":    "Conectando...",
        "s3_sin_ssid":    "Selecciona o ingresa una red WiFi.",
        "s3_sin_server":  "Ingresa la URL del servidor.",
        "s3_url_invalida": "URL inválida — usa http://host:puerto/ruta",
        "s3_escaneando":  "Buscando redes WiFi...",
        "s3_enviando_cfg":"Enviando configuración al ESP32...",
        "s3_ninguna_red": "No se encontraron redes",
        "s3_redes_found": "{n} redes encontradas — toca una para seleccionar",
        "s3_red_sel":     "seleccionada",
        "s3_cfg_ok":      "✓  Conectado — ID: {did}",
        "s3_srv_warn":    "⚠  El servidor {base} no responde desde esta PC (tu IP es {ip}). Corrige la URL en Configuración avanzada, o pulsa de nuevo para enviar de todos modos.",

        "s3_cal_toggle":    "▶  Calibración de sensores",
        "s3_cal_toggle_op": "▼  Calibración de sensores",
        "s3_cal_opcional":  "opcional",
        "s3_cal_hint":      "Ajusta si el sensor difiere de un instrumento de referencia.",
        "s3_cal_t_off":     "Offset temperatura (°C)",
        "s3_cal_h_off":     "Offset humedad aire (%)",
        "s3_cal_s_dry":     "ADC suelo seco  — SOIL_DRY",
        "s3_cal_s_wet":     "ADC suelo mojado — SOIL_WET",
        "s3_cal_btn":       "Guardar calibración en ESP32",
        "s3_cal_guardando": "Guardando calibración...",
        "s3_cal_invalidos": "Valores inválidos.",
        "s3_cal_soil_err":  "SOIL_DRY debe ser menor que SOIL_WET.",
        "s3_cal_ok":        "✓  Calibración guardada en ESP32.",

        "pins_btn":      "🔍  Detectar pines",
        "pins_busy":     "Escaneando pines del ESP32 (hasta 30 s)... Para detectar el FC-28, insértalo en tierra o toca sus puntas.",
        "pins_ok":       "✓  DHT11 → GPIO{dht}   ·   FC-28 → GPIO{soil}   (guardado en el dispositivo)",
        "pins_dht_no":   "✗  DHT11 no encontrado en ningún pin — revisa VCC/GND y el pin DATA.",
        "pins_soil_air": "⚠  FC-28 posiblemente en GPIO{soil} (señal débil — está en aire). Insértalo en tierra y repite.",
        "pins_soil_no":  "✗  FC-28 no encontrado — debe ir en un pin ADC1 (GPIO 32–39).",
        "pins_err":      "✗  Detección de pines falló: {err}",

        "s4_header":    "Verificación de sensores",
        "s4_sub":       "Confirma que los sensores están bien conectados antes de empaquetar.",
        "s4_col_sensor":"Sensor",
        "s4_col_val":   "Lectura",
        "s4_col_st":    "Estado",
        "s4_sensors":   [
            "DHT11 — Temperatura",
            "DHT11 — Humedad del aire",
            "FC-28 — Humedad del suelo",
        ],
        "s4_btn_test":    "▶  Testear sensores",
        "s4_leyendo":     "Leyendo...",
        "s4_hint_test":   "Presiona ▶ Testear para verificar los sensores.",
        "s4_qr_err":      "Error al generar QR",
        "s4_qr_ph":       "QR\naquí",
        "s4_btn_save_qr": "Guardar PNG",
        "s4_qr_title":    "Guardar QR como PNG",
        "s4_btn_listo":   "Marcar como LISTO  ✓",
        "s4_listo_done":  "✓  Listo",
        "s4_wifi_lbl":    "WiFi:",
        "s4_server_lbl":  "Servidor:",
        "s4_port_lbl":    "Puerto:",
        "s4_test_errs":   "✗  {n} sensor(es) con error — revisa el cableado.",
        "s4_test_warns":  "⚠  Sensores OK con {n} advertencia(s).",
        "s4_test_ok":     "✓  Todos los sensores responden correctamente.",
        "s4_serial_listen":   "Escuchando lecturas del ESP32 por USB (hasta 30 s)...",
        "s4_waiting_srv":     "Esperando datos del sensor vía servidor... {s}s",
        "s4_srv_unreachable": "✗  El servidor {base} no responde desde esta PC. Verifica que el backend esté corriendo. La IP de esta PC es {ip} — úsala en la URL del servidor (paso 3).",
        "s4_no_did":          "✗  Sin ID de dispositivo. Completa el paso 3 primero.",
        "s4_no_data":         "✗  El ESP32 no envió datos. ¿Está conectado al WiFi y al servidor?",
        "s4_qr_saved":    "QR guardado: {name}",
        "s4_batch_reg":   "Dispositivo #{n} registrado correctamente.",
        "s4_btn_export":  "⬇  Exportar datos",
        "s4_export_title":"Guardar telemetría como CSV",
        "s4_export_busy": "Capturando telemetría por USB (~60 s)... {n} lecturas",
        "s4_export_ok":   "✓  {n} lecturas exportadas a {name}",
        "toast_export_t": "Datos exportados",

        "s5_header":     "Activar en TerraSense",
        "s5_sub":        "Último paso — inicia sesión para abrir el sistema directamente en el navegador.",
        "s5_srv_detect":  "Servidor detectado",
        "s5_web_url":     "URL de TerraSense Web",
        "s5_email":       "Email",
        "s5_pass":        "Contraseña",
        "s5_ph_email":    "tu@email.com",
        "s5_ph_web":      "http://localhost:3000",
        "s5_btn_conectar":"Conectar y abrir TerraSense  →",
        "s5_conectando":  "Conectando...",
        "s5_reintento":   "Reintentar  →",
        "s5_sin_creds":   "✗  Completa email y contraseña.",
        "s5_logging_in":  "Iniciando sesión en TerraSense...",
        "s5_no_token":    "La respuesta no contiene token",
        "s5_success_ttl": "Listo",
        "s5_success_inf": (
            "El navegador se abrió con tu sesión activa.\n"
            "Tu dispositivo aparece en Dispositivos pendientes."
        ),
        "s5_btn_reabrir": "Abrir TerraSense de nuevo  →",
        "s5_btn_volver":  "Volver al formulario",
        "s5_bienvenido":  "Bienvenido, {nombre}",
        "s5_http_err":    "✗  Error {code}: credenciales incorrectas o servidor no disponible.",
        "s5_http_warn":   "Servidor en http:// — los datos viajarán sin cifrar.",

        "s4_dht_first":   "✗  El DHT11 no responde: revisa VCC→3V3, GND→GND y DATA en su pin. El suelo no se evalúa hasta que el DHT11 funcione.",

        "toast_flash_t":    "Firmware grabado",
        "toast_flash_d":    "Esperando reinicio y detectando sensores...",
        "toast_pins_t":     "Detección de sensores",
        "toast_cfg_t":      "WiFi configurado",
        "toast_dev_t":      "ESP32 detectado",
        "toast_listo_t":    "Dispositivo registrado",
        "toast_login_t":    "Sesión iniciada",
        "toast_test_t":     "Test de sensores",
        "toast_test_err_t": "Sensores con error",
        "toast_err_t":      "Error",

        "sin_puerto":        "Sin puerto.",
        "puerto_ocupado":    "⏳  El puerto está ocupado por otra operación en curso. Espera a que termine e inténtalo de nuevo.",
        "nuevo_dispositivo": "--- Nuevo dispositivo ---\n",
    },

    "en": {
        "app_title":          "AgroCommish",
        "configurador_iot":   "IoT Configurator",
        "unidades_listas":    "units ready",
        "lang_btn":           "ES",

        "step_1": "Detect",
        "step_2": "Flash",
        "step_3": "Configure",
        "step_4": "Verify",
        "step_5": "Activate",

        "btn_anterior":          "← Back",
        "btn_continuar":         "Continue →",
        "btn_nuevo_dispositivo": "+ New device",

        "s1_header":   "Connect ESP32 via USB",
        "s1_sub":      "Detected automatically when connected. Compatible with USB-A and USB-C.",
        "s1_esperando":"Waiting for device... connect the ESP32 via USB",
        "s1_sin_dev":  "(no devices)",
        "s1_port_no_driver": "Port detected — may need ESP32 driver",

        "s2_header":          "Flash Firmware",
        "s2_sub":             "Flash the firmware and the app will detect the device and its sensors automatically.",
        "s2_btn_seleccionar": "Change",
        "s2_btn_grabar":      "Flash Firmware",
        "s2_grabando":        "Flashing...",
        "s2_reintento":       "Retry",
        "s2_ok":              "\n✓  Firmware flashed successfully.",
        "s2_fw_ok":           "✓  Firmware ready to flash",
        "s2_fw_missing":      "⚠  firmware.bin not found — select the file",
        "s2_log_label":       "Process log",
        "s2_err_sin_puerto":  "ERROR: Select a port first.",
        "s2_err_fw_noexiste": "ERROR: Firmware file does not exist at the specified path.",
        "s2_log_puerto": "Port: {port}",
        "s2_log_fw":     "Firmware: {fw}",
        "s2_boot_wait":    "⏳  Waiting for the ESP32 to reboot...",
        "s2_dev_id":       "✓  Device detected: {did}",
        "s2_boot_timeout": "⚠  The ESP32 did not respond after flashing: {err}\n   Continue with step 3 and try scanning networks.",
        "s2_pins_scan":    "🔍  Finding which pins the sensors are connected to...",
        "s2_fase_conectando": "Connecting to the ESP32...",
        "s2_fase_borrando":   "Erasing flash memory (this takes a few seconds)...",
        "s2_fase_grabando":   "Writing firmware...",
        "s2_fase_verificado": "✓  Data verification passed",
        "s2_fase_listo":      "✓  Flashing complete",
        "fw_title":      "Select firmware .bin",
        "fw_filter":     "ESP32 Firmware",

        "s3_header":      "Connect to WiFi",
        "s3_sub":         "Select your network, enter the password and connect the ESP32.",
        "s3_lbl_redes":   "Available networks",
        "s3_lbl_pass":    "Password",
        "s3_ph_pass":     "WiFi network password",
        "s3_ph_server":   "http://192.168.1.100:5000/api/sensores/lectura",
        "s3_adv_server":  "Advanced server settings",
        "s3_btn_escanear":"Search networks",
        "s3_btn_conectar":"Connect to WiFi →",
        "s3_btn_enviar":  "Connect to WiFi →",
        "s3_enviando":    "Connecting...",
        "s3_sin_ssid":    "Select or enter a WiFi network.",
        "s3_sin_server":  "Enter the server URL.",
        "s3_url_invalida": "Invalid URL — use http://host:port/path",
        "s3_escaneando":  "Searching for WiFi networks...",
        "s3_enviando_cfg":"Sending configuration to ESP32...",
        "s3_ninguna_red": "No networks found",
        "s3_redes_found": "{n} networks found — tap one to select",
        "s3_red_sel":     "selected",
        "s3_cfg_ok":      "✓  Connected — ID: {did}",
        "s3_srv_warn":    "⚠  Server {base} is not responding from this PC (your IP is {ip}). Fix the URL under Advanced settings, or press again to send anyway.",

        "s3_cal_toggle":    "▶  Sensor calibration",
        "s3_cal_toggle_op": "▼  Sensor calibration",
        "s3_cal_opcional":  "optional",
        "s3_cal_hint":      "Adjust if sensor reading differs from a reference instrument.",
        "s3_cal_t_off":     "Temperature offset (°C)",
        "s3_cal_h_off":     "Air humidity offset (%)",
        "s3_cal_s_dry":     "Dry soil ADC — SOIL_DRY",
        "s3_cal_s_wet":     "Wet soil ADC — SOIL_WET",
        "s3_cal_btn":       "Save calibration to ESP32",
        "s3_cal_guardando": "Saving calibration...",
        "s3_cal_invalidos": "Invalid values.",
        "s3_cal_soil_err":  "SOIL_DRY must be less than SOIL_WET.",
        "s3_cal_ok":        "✓  Calibration saved to ESP32.",

        "pins_btn":      "🔍  Detect pins",
        "pins_busy":     "Scanning ESP32 pins (up to 30 s)... To detect the FC-28, insert it into soil or touch its probes.",
        "pins_ok":       "✓  DHT11 → GPIO{dht}   ·   FC-28 → GPIO{soil}   (saved on device)",
        "pins_dht_no":   "✗  DHT11 not found on any pin — check VCC/GND and the DATA pin.",
        "pins_soil_air": "⚠  FC-28 possibly on GPIO{soil} (weak signal — it is in air). Insert into soil and retry.",
        "pins_soil_no":  "✗  FC-28 not found — it must be on an ADC1 pin (GPIO 32–39).",
        "pins_err":      "✗  Pin detection failed: {err}",

        "s4_header":    "Sensor Verification",
        "s4_sub":       "Confirm sensors are properly connected before packaging.",
        "s4_col_sensor":"Sensor",
        "s4_col_val":   "Reading",
        "s4_col_st":    "Status",
        "s4_sensors":   [
            "DHT11 — Temperature",
            "DHT11 — Air Humidity",
            "FC-28 — Soil Humidity",
        ],
        "s4_btn_test":    "▶  Test sensors",
        "s4_leyendo":     "Reading...",
        "s4_hint_test":   "Press ▶ Test to verify the sensors.",
        "s4_qr_err":      "Error generating QR",
        "s4_qr_ph":       "QR\nhere",
        "s4_btn_save_qr": "Save PNG",
        "s4_qr_title":    "Save QR as PNG",
        "s4_btn_listo":   "Mark as DONE  ✓",
        "s4_listo_done":  "✓  Done",
        "s4_wifi_lbl":    "WiFi:",
        "s4_server_lbl":  "Server:",
        "s4_port_lbl":    "Port:",
        "s4_test_errs":   "✗  {n} sensor(s) with error — check the wiring.",
        "s4_test_warns":  "⚠  Sensors OK with {n} warning(s).",
        "s4_test_ok":     "✓  All sensors responding correctly.",
        "s4_serial_listen":   "Listening for ESP32 readings over USB (up to 30 s)...",
        "s4_waiting_srv":     "Waiting for sensor data via server... {s}s",
        "s4_srv_unreachable": "✗  Server {base} is not responding from this PC. Check that the backend is running. This PC's IP is {ip} — use it in the server URL (step 3).",
        "s4_no_did":          "✗  No device ID. Complete step 3 first.",
        "s4_no_data":         "✗  The ESP32 did not send data. Is it connected to WiFi and the server?",
        "s4_qr_saved":    "QR saved: {name}",
        "s4_batch_reg":   "Device #{n} registered successfully.",
        "s4_btn_export":  "⬇  Export data",
        "s4_export_title":"Save telemetry as CSV",
        "s4_export_busy": "Capturing USB telemetry (~60 s)... {n} readings",
        "s4_export_ok":   "✓  {n} readings exported to {name}",
        "toast_export_t": "Data exported",

        "s5_header":     "Activate in TerraSense",
        "s5_sub":        "Last step — log in to open the system directly in the browser.",
        "s5_srv_detect":  "Detected server",
        "s5_web_url":     "TerraSense Web URL",
        "s5_email":       "Email",
        "s5_pass":        "Password",
        "s5_ph_email":    "you@email.com",
        "s5_ph_web":      "http://localhost:3000",
        "s5_btn_conectar":"Connect and open TerraSense  →",
        "s5_conectando":  "Connecting...",
        "s5_reintento":   "Retry  →",
        "s5_sin_creds":   "✗  Enter your email and password.",
        "s5_logging_in":  "Logging in to TerraSense...",
        "s5_no_token":    "Response does not contain a token",
        "s5_success_ttl": "Done",
        "s5_success_inf": (
            "The browser opened with your session active.\n"
            "Your device appears in Pending Devices."
        ),
        "s5_btn_reabrir": "Open TerraSense again  →",
        "s5_btn_volver":  "Back to form",
        "s5_bienvenido":  "Welcome, {nombre}",
        "s5_http_err":    "✗  Error {code}: wrong credentials or server unavailable.",
        "s5_http_warn":   "Server on http:// — data will travel unencrypted.",

        "s4_dht_first":   "✗  DHT11 not responding: check VCC→3V3, GND→GND and DATA on its pin. Soil is not evaluated until the DHT11 works.",

        "toast_flash_t":    "Firmware flashed",
        "toast_flash_d":    "Waiting for reboot and detecting sensors...",
        "toast_pins_t":     "Sensor detection",
        "toast_cfg_t":      "WiFi configured",
        "toast_dev_t":      "ESP32 detected",
        "toast_listo_t":    "Device registered",
        "toast_login_t":    "Logged in",
        "toast_test_t":     "Sensor test",
        "toast_test_err_t": "Sensors with errors",
        "toast_err_t":      "Error",

        "sin_puerto":        "No port selected.",
        "puerto_ocupado":    "⏳  The port is busy with another ongoing operation. Wait for it to finish and try again.",
        "nuevo_dispositivo": "--- New device ---\n",
    },
}

_current: str = "es"


def set_lang(lang: str) -> None:
    global _current
    if lang in STRINGS:
        _current = lang


def get_lang() -> str:
    return _current


def T(key: str, **kwargs):
    val = STRINGS.get(_current, STRINGS["es"]).get(key)
    if val is None:
        val = STRINGS["es"].get(key, key)
    if isinstance(val, str) and kwargs:
        return val.format(**kwargs)
    return val
